### ISSUE TITLE
BrokerBinaryProvider.getBinary(TCMURI binaryUri, BinaryMeta binaryMeta) always fetches the default variant [Web 8]

### ISSUE THREAD

**Issue by Dretch** [dd4t/dd4t-2-java#110]
I have a problem where `AbstractBinaryController` always serves the "default" image size, rather than using the correct variant from the CMS.

I have traced the problem back to `BrokerBinaryProvider.getBinary(TCMURI binaryUri, BinaryMeta binaryMeta)`. This method ignores the variant (obtainable from `binaryMeta.getVariantId()`) and so the underlying SDL libraries just return the "default" variant.

I have fixed the problem locally by making a custom `BrokerBinaryProvider` that does not ignore the variant. I can send a pull request with this change, if you like -- but I am not sure if this change will break something else. Is it simply an oversight that the variant was ignored, or is there a reason for it?

**Comment by RaimondKempees** [comment]
Happy to review a PR on short notice and build a release.
 
I think what would be good is to leave the current method as is for backward compatibility and maybe add a new one, overloaded for loading variants.
 
The reason this wasn’t in the provider was simply because it wasn’t needed before by anyone, so am happy to start supporting it. :)

**Comment by Dretch** [comment]
> I think what would be good is to leave the current method as is for backward compatibility and maybe add a new one, overloaded for loading variants.

I have investigated doing this. It would require adding something like `getBinaryVariantByURL(String url, int publicationId)` to `BinaryFactory` and a similar method to `BinaryProvider`. These methods seem redundant to me since `getBinaryByURL(String url, int publication)` already get passed the information about which variant to use (it's in the URL).

I would prefer to change only `BrokerBinaryProvider` to make it fetch variants when they are given. This would not be completely backwards compatible because it means anyone relying on the old behaviour of the default variant always being fetched will discover they now receive the variant they actually asked for... If such users want to keep the old behaviour they will have the option of switching to `BinaryProvider.getBinaryByURI`, which will continue to fetch the default variant (because, I believe, TCM URIs don't contain variant information).

**Comment by quirijnslings** [comment]
The getBinaryByUrl method should not be called with a variant ID at all. The .NET version of DD4T does it like this:
1. The (Tridion) BinaryMetaFactory .GetMetaByUrl method is called with the URL only (string)
2. This method looks in the BinaryVariants table for a variant with that URL (within the publication, separate story)
3. It returns a BinaryMeta object (also from the Tridion namespace), which contains a property VariantId)
4. If VariantId is null, the (Tridion) BinaryFactory is called to retrieve the binary by Id without specifying a VariantId
5. If VariantId is not null, the BinaryFactory is called to retrieve the binary by Id and VariantId

@RaimondKempees Is there a reason not to do it this way in Java?

**Comment by RaimondKempees** [comment]
@quirijnslings, @Dretch - is this what you had in mind: https://github.com/dd4t/dd4t-2-java/commit/8951be3385875df7552488a6950050349259db47 ?

**Comment by Dretch** [comment]
@RaimondKempees That is pretty much exactly what I had in mind! 👍

**Comment by quirijnslings** [comment]
Your change applies to Web 8 microservice architecture only.

For in-process and legacy implementations, you need to change line 106 of the BrokerBinaryProvider in the dd4t-providers module to:

content = contentDAO.findByPrimaryKey(binaryUri.getPublicationId(), binaryUri.getItemId(), binaryVariant.getVariantId());

I've tested this and it works. Do you want me to commit my change or will you do it yourself, @RaimondKempees?

**Comment by RaimondKempees** [comment]
Fixed and available in 2.1.4
