### ISSUE TITLE
dd4t core includes com.tridion.cache.CacheEvent class, leading to serialization issues

### ISSUE THREAD

**Issue by mvanderwal** [dd4t/dd4t-2-java#12]
In the dd4t-core module a class is included which also exists in the standard Tridion product jar files: com.tridion.cache.CacheEvent (part of Tridion cd_cache.jar).

Even though both versions are the same on source level this still leads to issues in certain cases. As both versions do not define a serialVersionUID these are generated on compile time. And (depending on compiler, etc) are not the same.

In our scenario we are using JMS queues for cache invalidation. The CacheEvent is serialized and sent as a JMS message. This currently does not work because it throws java.io.InvalidClassException with two different serialVersionUID values (one that matches the compiled version in the DD4T jar and one that matches the compiled version in the Tridion jar). The sender (deployer) sends the original Tridion versoin and the receiver (webapp) uses the DD4T version.

Ideally the com.tridion.cache.CacheEvent class should not be included in the DD4T jars. So the best solution would be to remove this. If this is not possible then the alternative would be to include a serialVersionUID which matches the one that is in the Tridion provided jar (however, this could break very easily anytime an updated version of the Tridion jar is used).

**Comment by RaimondKempees** [comment]
Hi @mvanderwal,

I've been thinking about this for a while now and I've got a couple of questions:

1. Which JMS queue / broker do you use? In ActiveMQ this has been no issue
2. In which class do you see the java.io.InvalidClassException happening?

Further, I agree with you that we shouldn't actually have that class in the dd4t stack, but as we want to keep the dd4t-2 core tridion dependency independent, there unfortunately is no other way to do this. I also agree that we shouldn't play around with adding a serialVersionUID to the class, as that may differ - exactly because inside Tridion's cd_cache.jar there's no serialVersionUUID set. 

I'll try to figure out an elegant solution.

**Comment by mvanderwal** [comment]
We are using ActiveMQ and Tridion 2013SP1HR1.

See the attached image for the stack trace (sorry, due to technical limitations I can only copy it as an image),

![cacheissue](https://cloud.githubusercontent.com/assets/13993048/9681881/e4e6d2bc-5301-11e5-9b56-2d35febcff51.png)

**Comment by quirijnslings** [comment]
I may have a solution. I have created my own cachechannelconnector class to generate text messages. This is needed for .net anyway. Why don't we reuse it for java?
The text message contains serialised JSON. We can create a simple cache event class of our own in .NET as well as Java.
Only thing is it needs to be configured in the deployer, but that is a small price to pay.
The connector still needs some polishing but it is already working.

**Comment by RaimondKempees** [comment]
Let's keep that as a fall back option - indeed we should not go the way of having to configure the deployer for this. 

I'm currently working on another hack - I'll keep you posted!

**Comment by ThijsBorst** [comment]
JMS isn't configured by default... JMS isn't installed by default. Shouldn't be a problem to do a custom JMS implementation.

**Comment by RaimondKempees** [comment]
Which requires extra jar files and a setup not described in the SDL manuals..

**Comment by rogieroudshoorn** [comment]
If i remember correctly, that java class exists in the repository for the rest service setup. I would be very much inclined to move the class to the remote providers project (with the rest of the classes necessary to run dd4t scaled away from the tridion API). 

Concerning that error, what application server are you using? It appears a UID might be generated where it isn't in place already ...

**Comment by RaimondKempees** [comment]
@rogieroudshoorn, that is exactly the direction I'm taking, as it's only actually used then. Further, I'm investigating whether we would then still be in need of a custom JMS receiver to handle this. A custom JMS receiver can be made to ignore the serialVersionUUID altogether :)

@quirijnslings, @ThijsBorst - I understand it works differently in .Net, but I'd recommend to at all cost still try to prevent any custom stuff in the deployer.

@mvanderwal expect this fixed next week.

**Comment by RaimondKempees** [comment]
Hi @mvanderwal,

Would you be contactable over Skype or email? I have some more questions for you. :)

**Comment by mvanderwal** [comment]
Yes. Just add @sdl.com befind my github username.

I also have Skype but will share that once we are connected via email

**Comment by RaimondKempees** [comment]
I finally fixed this by moving the caching stuff dependent on com.tridion.cache.CacheEvent to its own module. Next, I deleted the CacheEvent class from the dd4t core module. 

When running dd4t with the Tridion stack, the cd_cache.jar loaded will provide the class. When there is no Tridion stack in the web app, all you have to do is include the dd4t-caching-rs module, which mocks the CacheEvent class.
