### ISSUE TITLE
Embedded field in embdded field is not mapped to view model on DD4T 2 Java version

### ISSUE THREAD

**Issue by HirokazuShikata** [dd4t/dd4t-2-java#13]
This issues is posted to StackExchange too.
http://tridion.stackexchange.com/questions/12859/embedded-field-in-embdded-field-is-not-mapped-to-view-model-on-dd4t-2-java-versi

Summary is following.
On DD4T 2 Java version environment, I created view model class. But, when there is a embedded field in another embedded field, 2nd embedded field values are not mapped to view model instance, and I got following error. (1st embedded field's value is mapped to view model instance normally.)

**Comment by RaimondKempees** [comment]
Your issue got me thinking on how we did deserialisation of embedded fields and how that should work with using ViewModels. While your code is correct and will work, I did some refactoring to make it a bit smoother. Please see the answer posted on StackExchange. :) Thanks for raising this!

The next release (2.0.2) will go out on the 28th, so it's immediately available in Maven Central then.
