### ISSUE TITLE
LastPublishDate in models

### ISSUE THREAD

**Issue by jhorsman** [dd4t/dd4t-2-java#14]
The DD4T JSON datamodel published by the Content Manager contains `LastPublishedDate` for pages, components, component links, etc. This `LastPublishedDate` is placeholder data since it cannot be published from the Content Manager, it has to be retrieved from the CD broker.

Currently the `LastPublishedDate` is not available in the DD4T models, or anywhere else in DD4T. It would be great to have this added.

Example: `"RevisionDate":"2015-03-17T10:39:15.827","Filename":"index","LastPublishedDate":"0001-01-01T00:00:00","PageTemplate":`

**Comment by jhorsman** [comment]
A workaround suggested by Quirijn: "you could write a 5 line TBB that sets the publish date in the json source code"

**Comment by quirijnslings** [comment]
Well, 8 lines on closer inspection.

```csharp
[TcmTemplateTitle("Add publish date to page")]
public partial class AddPublishDate : BasePageTemplate
{
    protected override void TransformPage(Dynamic.Page page)
    {
        page.LastPublishedDate = DateTime.Now;
    }
}
```

**Comment by quirijnslings** [comment]
@jhorsman is it okay to close this issue, or do you still want a fix?

**Comment by RaimondKempees** [comment]
I've fixed this for Pages and Binaries. If we need this also for Components inside DCPs, then please create a new issue.
