### ISSUE TITLE
Rework the ComponentPresentationProvider for the version 2 TBBs

### ISSUE THREAD

**Issue by RaimondKempees** [dd4t/dd4t-2-java#15]
Now that the DD4T TBBS support publishing a full ComponentPresentation node in the Json, we can remove the ugly hacks in https://github.com/dd4t/dd4t-2-java/blob/develop/dd4t-providers/src/main/java/org/dd4t/providers/impl/BrokerComponentPresentationProvider.java.

This provider should have **no** dependency anymore on the org.dd4t.contentmodel.ComponentPresentation model, but should give back a String with the uncompressed Json content, just as in the other providers

Note: be sure to handle the Component Template metadata properly!

**Comment by anbusampath** [comment]
We used dd4t 2.0.1-beta version initially, Now we are upgrading to 2.0.4 and updated the TBBs to v2.0.8. We published the content using the new template , but the content is still coming the same old way (i.e, without the ComponentTemplate). Hence JSON Binder not converting to view models properly.

We want to know what else needs to be done to publish the full ComponentPresentation node.

**Comment by RaimondKempees** [comment]
What is the Json you get out? I think its best to take this offline. Can
you send me a private message?

**Comment by anbusampath** [comment]
I am getting only Component data as JSON instead of Component and
ComponentTemplate.

Dont know how to send private message. Can you mail me to my email(
anbu.s27@gmail.com).

On 23 March 2016 at 12:58, RaimondKempees <notifications@github.com> wrote:

> What is the Json you get out? I think its best to take this offline. Can
> you send me a private message?
>
> On Wed, Mar 23, 2016 at 8:10 AM, anbusampath <notifications@github.com>
> wrote:
>
> > We used dd4t 2.0.1-beta version initially, Now we are upgrading to 2.0.4
> > and updated the TBBs to v2.0.8. We published the content using the new
> > template , but the content is still coming the same old way (i.e, without
> > the ComponentTemplate). Hence JSON Binder not converting to view models
> > properly.
> >
> > We want to know what else needs to be done to publish the full
> > ComponentPresentation node.
> >
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/dd4t/dd4t-2-java/issues/15#issuecomment-200219768>
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/dd4t/dd4t-2-java/issues/15#issuecomment-200227723>
>



-- 
--Anbu
