### ISSUE TITLE
Duplicated property 'dd4t.version'

### ISSUE THREAD

**Issue by andham** [dd4t/dd4t-2-java#29]
The 'dd4t.version' property is defined twice in the parent pom. You should remove the one having "2.0.0" hard-coded!

**Comment by andham** [comment]
Actually, looking through the pom files I see that the property isn't used at all. So it should be removed all together.

**Comment by andham** [comment]
There seems to be other duplicated properties as well, which should be removed. 'junit.version' for example.

**Comment by RaimondKempees** [comment]
Fixed on the beta-fixes branch.

**Comment by andham** [comment]
There are still several other duplicate properties: slf4j.version, javax.servlet-api.version, logback.version, spring.version, joda-time.version.

**Comment by RaimondKempees** [comment]
That's also sorted out now.
