### ISSUE TITLE
Need access to link resolving logic

### ISSUE THREAD

**Issue by quirijnslings** [dd4t/dd4t-2-java#37]
As a developer I need access to a class in the framework which allows me to resolve dynamic links. For example: my ViewModel needs a resolved link to A. the underlying component itself, and B. another component to which the underlying component links.

**Comment by RaimondKempees** [comment]
This can be done already by doing:

`LinkResolver linkResolver = (LinkResolver)JspBeanContext.getBean("linkResolver");`

It's not the nicest way, but it does work.

**Comment by RaimondKempees** [comment]
Investigate whether a nicer entry point is required.

**Comment by quirijnslings** [comment]
Can we have a ViewModelProperty which resolves a link to the current component? Like this perhaps:

	@ViewModelProperty(linkToCurrentComponent=true)
	private String url;

Or

	@LinkToCurrentComponent
	private String url;

**Comment by Dretch** [comment]
I have a similar use case. Maybe you could have something like:

```
@ViewModelProperty(resolveLink = ViewModelLinkResolution.Field)
private String url; // "url" is a component link field in the CMS
```

for resolving component link fields, and:

```
@ViewModelProperty(resolveLink = ViewModelLinkResolution.Parent)
private String url;
```

for resolving the URL to the component that underlies the current ViewModel.

I think parallel link resolution (of all the component links in the whole tree of ViewModels) would be nice, too - perhaps optionally via a pluggable `ViewModelLinkResolver` or something like that.

**Comment by RaimondKempees** [comment]
Solved. You can do:

`    @ViewModelProperty(isComponentLinkUrl = true)
    private String urlForThisComponent;
    @ViewModelProperty (entityFieldName = "componentlink")
    private AbstractModelClass componentLink;

    @ViewModelProperty(entityFieldName = "componentlink", resolveLinkForComponentLinkField = true)
    private String componentLinkUrl;

`
