### ISSUE TITLE
ViewModels are not created for DCPs

### ISSUE THREAD

**Issue by quirijnslings** [dd4t/dd4t-2-java#38]
If a DCP is retrieved through the ComponentFactory, ViewModels are never correctly created. They are either missing altogether, or they have only empty properties (which contain 'null'). 
The problem becomes apparent in the JsonModelConverter. This class checks for the ComponentType of the JSON object, to find out if it should look at the content AND metadata (for regular components) or the metadata only (for multimedia components). If the content comes from a DCP, there is no ComponentType property at all. As a result, the JsonModelConverter has no 'field list' at its disposal to look for the values for the specified properties.
Why the ComponentType property is missing, is unclear to me.

**Comment by RaimondKempees** [comment]
Fixed. Will be available in dd4t 2.0.4
