### ISSUE TITLE
XPM path missing for Component Field(MULTIMEDIALINK/COMPONENTLINK) in View Model

### ISSUE THREAD

**Issue by anbusampath** [dd4t/dd4t-2-java#49]
We have view model content Java class as follows, 
```
public class HomeHeader extends TridionViewModelBase {

    @ViewModelProperty(entityFieldName = "help_text")
    private String helpText;

    @ViewModelProperty(entityFieldName = "logo_image")
    private Component logoImage;

    @ViewModelProperty(entityFieldName = "banner_image")
    private Component bannerImage;
}
```
viewmodel bean class's FieldMap not having the XPath information for Component fields.(Even after changing Component type to  MultiMediaImpl or ComponentImpl , could not find XPath info).

```
{help_text=org.dd4t.databind.viewmodel.base.TridionViewModelBase$XPMInfo@63869a2e }
```
JSON as follows,
![json](https://cloud.githubusercontent.com/assets/1268973/14108978/7d5c796a-f5dd-11e5-8599-f810c6cb1545.png)

**Comment by RaimondKempees** [comment]
Fixed in 2.0.5.
