### ISSUE TITLE
Refactor publication resolving

### ISSUE THREAD

**Issue by RaimondKempees** [dd4t/dd4t-2-java#5]
Publication resolving is in need of a bit of an overhaul. Design an implement a proper generic way of resolving Publication Ids based on incoming URL information.

This issue **must** have unit tests for all flows where this is used, as this is more complex than it seems.

**Comment by RaimondKempees** [comment]
This is fixed for incoming Page URLs.

The more challenging part is to find a publication Id based on part of the path.

**Comment by willprice76** [comment]
You can use combination of domain+port+rootPath to get publication id via the CD API - should be somewhere in the DXA Java code base...

**Comment by RaimondKempees** [comment]
Doing that already :) does require config of cd_dynamic_conf.xml and need to check whether that's in Tridion 2011 and whether we support it still. Thanks!
