### ISSUE TITLE
BrokerBinaryProvider does not return binaries

### ISSUE THREAD

**Issue by quirijnslings** [dd4t/dd4t-2-java#50]
There are 2 major bugs in this class:

1. The method "private Binary getBinary" contains the following line:

binaryDataBytes.setBytes(getBinaryContentById(binaryUri.getPublicationId(), binaryUri.getItemId()));

However, the signature of the getBinaryContentById method puts the ITEM id first and the PUBLICATION id second. No binaries are ever retrieved.

2.The method "public byte[] getBinaryContentById" contains the following code:

if (binaryData == null || binaryData.getDataSize() > 0 ) {
    throw new ItemNotFoundException("Unable to find binary content by id: tcm:" + publication+"-"+id);
}

This means that an exception is thrown for binaries with a data size of MORE than 0. In other words: valid binaries always lead to an item not found exception.

**Comment by RaimondKempees** [comment]
Fixed. Release will happen in a few hours
