### ISSUE TITLE
Binary.getLastPublishedDate always returns 'now'

### ISSUE THREAD

**Issue by quirijnslings** [dd4t/dd4t-2-java#51]
The following code returns 2 different values for 'millis'. The values always represent 'now'.

Binary binary = brokerBinaryProvider.getBinaryByURL (binaryurl, 1);
System.out.println(binary.getLastPublishedDate().getMillis());
// wait for a second
binary = brokerBinaryProvider.getBinaryByURL (binaryurl, 1);
System.out.println(binary.getLastPublishedDate().getMillis());

In our implementation, we never get the real last published date. Could it be that this only works for multimedia components that are published as a DCP?

**Comment by anbusampath** [comment]
We also seen that lastPublishedDate always return as current date. Images are published into file system in out implementation and part. Optimization happens for each image request . So we customized as follows, 
`
ItemDAO itemDao = (ItemDAO) StorageManagerFactory.getDAO(publicationId, StorageTypeMapping.ITEM_META);
                ItemMeta item = itemDao.findByPrimaryKey(publicationId, new TCMURI(binary.getId()).getItemId());
`

`                File binaryFile = new File(path);
                if (!binaryFile.exists()
                    || item.getLastPublishDate().compareTo(new Date(binaryFile.lastModified())) > 0) {...}
`

**Comment by RaimondKempees** [comment]
I am looking into it.

**Comment by RaimondKempees** [comment]
It works for me in 2.0.4 and 2.0.5-SNAPSHOT on normal Multimedia Component Meta as well as dynamically published DCPs for Multimedia. Which versions are you using?

**Comment by anbusampath** [comment]
2.0.1-beta , now we are migrating to 2.0.4

**Comment by quirijnslings** [comment]
We're using the 2.0.5-SNAPSHOT you sent us earlier.
Q

Date: Tue, 3 May 2016 03:35:36 -0700

**Comment by RaimondKempees** [comment]
Thanks. Are you both using either the in-process or CIL jar files for Web 8 ?

**Comment by anbusampath** [comment]
I am using Tridion 7.1.0 jar

On 3 May 2016 at 16:41, RaimondKempees <notifications@github.com> wrote:

> Thanks. Are you both using either the in-process or CIL jar files for Web
> 8 ?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/dd4t/dd4t-2-java/issues/51#issuecomment-216497701>
>



-- 
--Anbu

**Comment by RaimondKempees** [comment]
Can you guys check whether the **revisionDate** is set at all in the JSon?

**Comment by anbusampath** [comment]
I could see revisionDate in binary

![image](https://cloud.githubusercontent.com/assets/1268973/15072592/716fcd5e-13b1-11e6-80ed-7739ce747d88.png)

**Comment by RaimondKempees** [comment]
@quirijnslings, @anbusampath, is this still happening in 2.0.5?

**Comment by anbusampath** [comment]
No its not happening

**Comment by RaimondKempees** [comment]
Seems fixed.
