### ISSUE TITLE
Custom Component MetaData deserialization failure during JSON binding

### ISSUE THREAD

**Issue by anbusampath** [dd4t/dd4t-2-java#52]
#We are having component metadata field called 'session' which is dropdown in Tridion CMS. we are upgrading to DD4T 2.0.4 version(Earlier version 2.0.1-beta) and got below exception,

`java.io.IOException: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of org.dd4t.contentmodel.Keyword, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information
 at [Source: N/A; line: -1, column: -1] (through reference chain: org.dd4t.contentmodel.impl.ComponentImpl["MetadataFields"]->java.util.LinkedHashMap["session"]->org.dd4t.contentmodel.impl.KeywordField["Keywords"]->java.util.ArrayList[0])
	at org.dd4t.databind.serializers.json.ComponentPresentationDeserializer.renderComponentData(ComponentPresentationDeserializer.java:129) ~[ComponentPresentationDeserializer.class:na]
	at org.dd4t.databind.serializers.json.ComponentPresentationDeserializer.deserialize(ComponentPresentationDeserializer.java:113) ~[ComponentPresentationDeserializer.class:na]
	at org.dd4t.databind.serializers.json.ComponentPresentationDeserializer.deserialize(ComponentPresentationDeserializer.java:46) ~[ComponentPresentationDeserializer.class:na]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736) ~[ObjectMapper.class:2.6.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726) ~[ObjectMapper.class:2.6.4]
	at org.dd4t.databind.builder.json.JsonDataBinder.buildComponentPresentation(JsonDataBinder.java:94) ~[JsonDataBinder.class:na]
	at org.dd4t.databind.DataBindFactory.buildDynamicComponentPresentation(DataBindFactory.java:60) [DataBindFactory.class:na]`

Session Type Schema Definition:
![image](https://cloud.githubusercontent.com/assets/1268973/14951660/41589434-1078-11e6-9971-a318713c8bef.png)

Published JSON content for session Type:

   ` "session": {
      "Name": "session",
      "Value": "MORNING",
      "Values": [
        "MORNING"
      ],
      "NumericValues": [],
      "DateTimeValues": [],
      "LinkedComponentValues": [],
      "FieldType": 3,
      "CategoryName": "Session Type",
      "CategoryId": "tcm:123-1234-512",
      "XPath": "tcm:Metadata/custom:Metadata/custom:session",
      "Keywords": [
        {
          "Description": "",
          "Key": "",
          "TaxonomyId": "tcm:123-1234-512",
          "Path": "\\Session\\MORNING",
          "ParentKeywords": [],
          "MetadataFields": {
            "order": {
              "Name": "order",
              "Value": "1",
              "Values": [
                "1"
              ],
              "NumericValues": [
                1
              ],
              "DateTimeValues": [],
              "LinkedComponentValues": [],
              "FieldType": 8,
              "Keywords": [],
              "KeywordValues": []
            }
          },
          "Id": "tcm:123-1234-1024",
          "Title": "MORNING"
        }
      ],
      "KeywordValues": [
        {
          "Description": "",
          "Key": "",
          "TaxonomyId": "tcm:123-1234-512",
          "Path": "\\Session\\Morning",
          "ParentKeywords": [],
          "MetadataFields": {
            "order": {
              "Name": "order",
              "Value": "1",
              "Values": [
                "1"
              ],
              "NumericValues": [
                1
              ],
              "DateTimeValues": [],
              "LinkedComponentValues": [],
              "FieldType": 8,
              "Keywords": [],
              "KeywordValues": []
            }
          },
          "Id": "tcm:123-1234-1024",
          "Title": "MORNING"
        }
      ]
    }`

TBB version 2.0.8

I am guessing this issue occurs because of  `@JsonSetter ("Keywords")` at line 231 points to interface instead of class, may be we need to add `@JsonDeserialize (contentAs = KeywordImpl.class) ` (I am yet to customize and test it whether it works or not)

https://github.com/dd4t/dd4t-2-java/blob/develop/dd4t-core/src/main/java/org/dd4t/contentmodel/impl/BaseField.java

**Comment by RaimondKempees** [comment]
The concrete class is set on the property like so:

` @JsonDeserialize (contentAs = KeywordImpl.class)
    private List<Keyword> keywordValues;`

So, I am sure that is not the issue (it also just works in all Unit tests). I will investigate further.

**Comment by RaimondKempees** [comment]
If I compare your Json with what's coming out of the DD4T 2.0.8 templates, I see subtle differences:

`                    "keyword": {
                        "Name": "keyword",
                        "Values": ["Red"],
                        "NumericValues": [],
                        "DateTimeValues": [],
                        "LinkedComponentValues": [],
                        "FieldType": 3,
                        "CategoryName": "Colors",
                        "CategoryId": "tcm:7-1020-512",
                        "XPath": "tcm:Content/custom:Generic/custom:keyword",
                        "KeywordValues": [{
                            "Description": "",
                            "Key": "",
                            "TaxonomyId": "tcm:7-1020-512",
                            "Path": "\\Colors\\Red",
                            "ParentKeywords": [],
                            "MetadataFields": {},
                            "Id": "tcm:7-2114-1024",
                            "Title": "Red"
                        }]
                    }`

Can you check whether the component or page was republished against the 2.0.8 templates?

**Comment by anbusampath** [comment]
We looked at the session's  metadata schema definition, 'session' type category having been configured with a metadata 'order' (at level 010).

The issue arises if the metadata field is configured with a custom category which in-turn has a metadata in it.

Currently we removed the order meta data from the session and it worked.

**Comment by RaimondKempees** [comment]
Tested and seems fixed.
