### ISSUE TITLE
Question: AbstractPageController getPageViewName viewName?

### ISSUE THREAD

**Issue by TheMiXeD** [dd4t/dd4t-2-java#53]
Inside DD4T 2.0.4 and lower (checked till 2.0.2)
the class org.dd4t.mvc.controllers.AbstractPageController and method getPageViewName
There is a hardcode look for metadata **viewName**.

With the template: [2.0.8](https://github.com/dd4t/DD4T.TridionTemplates/releases)
There is no meta schema in there that provides this field and it's not documented.

Do I have to create this myself?

**Comment by RaimondKempees** [comment]
If you want your page view (JSP) to be different than the Tridion page template title, then indeed, you have to add your own Metadata Schema, with "viewName" as key.

It would be nice to make it the key (viewName) configurable, but that can be done on the basis of popular demand. ;)

**Comment by TheMiXeD** [comment]
Thank you
