### ISSUE TITLE
AbstractPageController seBlank() method 

### ISSUE THREAD

**Issue by anbusampath** [dd4t/dd4t-2-java#54]
Do we require seBlank() method in AbstractPageController class ?

We have scenario where we extend AbstractPageController and override show method in all controllers(To populate custom attributes in model and call super class show method to retrieve the page content).

When we extend AbstractPageController more than one controller, we are getting URL mapping issue, because /se_blank.html url inherited in both controllers.

**Comment by RaimondKempees** [comment]
I'll create a separate SEController. How does that sound?

**Comment by anbusampath** [comment]
Yes, that sounds good. So will you be removing the seBlank()  method from AbstractPageController in 2.0.5 release ?

**Comment by RaimondKempees** [comment]
Yup. Created an SeBlankController.
