### ISSUE TITLE
Cannot get "Target Group" condition(Java version)

### ISSUE THREAD

**Issue by HirokazuShikata** [dd4t/dd4t-2-java#57]
Even if "Target Group" is applied to a component presentation, cannot get it in DD4T Java version. 
"Target Group" condition is not de-serialized to Java object.

Detail is in following StackExchange post.
[http://tridion.stackexchange.com/questions/14242/how-to-do-personalization-on-dd4t-java-2-0](http://tridion.stackexchange.com/questions/14242/how-to-do-personalization-on-dd4t-java-2-0)

**Comment by RaimondKempees** [comment]
Will be added to 2.0.5-SNAPSHOT release this week.

**Comment by RaimondKempees** [comment]
Hi @HirokazuShikata,

I've added the code and released 2.0.5-SNAPSHOT in the staging repository of Maven Central. Could you verify?

**Comment by RaimondKempees** [comment]
@HirokazuShikata, version 2.0.5 is out. Can you please test this before I close this issue?
