### ISSUE TITLE
Question: How to get Metadata of Multimedia Schema

### ISSUE THREAD

**Issue by TheMiXeD** [dd4t/dd4t-2-java#59]
Inside Tridion 2013 SP1 we have a:
Multimedia Schema "Image" with Metadata "attributes" type Embedded Schema 

From Java application running DD4T 2.0.4
How to retrieve the values inside the Embedded Schema "attributes"

**Comment by TheMiXeD** [comment]
Inside the ViewModel changed Multimedia into Component.
Now there is the possibility to access the Metadata.

Now running into how to convert the Textfield into a String

**Comment by TheMiXeD** [comment]
Request for get value instead of valeus.get(0)

**Comment by RaimondKempees** [comment]
Hi @TheMiXeD, is this the same issue as issue #68 ?

**Comment by RaimondKempees** [comment]
In 2.0.6, you can now get metadata by creating your own viewmodel which has to have the basic Mulitmedia properties like Url, Width, Height in them as well:

`@ViewModel
public class Image extends TridionViewModelBase {

    // the focusPoint field is a metadata field in the MM component
    @ViewModelProperty(isMetadata = true)
    private String focusPoint;
    
    @ViewModelProperty(entityFieldName = "Url")
    private String url;


    @ViewModelProperty(entityFieldName = "Height")
    private int height;

    @ViewModelProperty(entityFieldName = "Width")
    private int width;

    @ViewModelProperty(entityFieldName = "Size")
    private Integer size;`
