### ISSUE TITLE
SerializerFactory.java serializer is null

### ISSUE THREAD

**Issue by TheMiXeD** [dd4t/dd4t-2-java#62]
Inside the dispatcher-serlet:
`<bean id="serializerFactory" class="org.dd4t.core.serializers.impl.SerializerFactory">
    <constructor-arg name="serializerInstance" ref="serializer"/>
  </bean>`

Inside SerializerFactory:
`public SerializerFactory (final JSONSerializer serializerInstance) {}`

The serializer = null when called

**Comment by TheMiXeD** [comment]
Adjusted the configuration and the factory itself. Fixed matching test where dependent on static setter
#63

**Comment by TheMiXeD** [comment]
Anybody here?

**Comment by RaimondKempees** [comment]
We're on holiday ;) back next week!

**Comment by RaimondKempees** [comment]
Merged the pull request. Thanks!

**Comment by TheMiXeD** [comment]
Your welcome
