### ISSUE TITLE
Feature request: generic getPage method

### ISSUE THREAD

**Issue by quirijnslings** [dd4t/dd4t-2-java#64]
Sometimes you want to create your own implementation of the Page interface. Unfortunately, that means you also need to implement/override the PageFactory, because the out of the box version explicitly deserializes against PageImpl (the default implementation of Page):

page = deserialize(pageSource, PageImpl.class);

It would be great to add an overload to the getPage method in the PageFactoryImpl. Something like this:

public Page getPage <T extends Page>(String uri) throws FactoryException {...}

In the method, we could retrieve the T dynamically and convert to a Type object, then pass that to the deserialize method.

See http://tridion.stackexchange.com/questions/14854/dd4t-2-java-java-lang-classcastexception/14856?noredirect=1#comment18691_14856

**Comment by RaimondKempees** [comment]
Fixed in 2.0.6
