### ISSUE TITLE
It is not possible to model your own multimedia classes

### ISSUE THREAD

**Issue by quirijnslings** [dd4t/dd4t-2-java#68]
The following code in the ComponentImpl has the undesired effect that the Multimedia property is only set if the ViewModel class is MultimediaImpl. If you want to model your own multimedia components (e.g. with custom metadata fields), the Multimedia property is always null.

 
   @JsonProperty ("Multimedia")
    @JsonDeserialize (as = MultimediaImpl.class)
    private Multimedia multimedia;

To solve, there should be a condition like 'instanceof = Multimedia' instead of 'as = MultimediaImpl.class' (if there is such a thing).

**Comment by quirijnslings** [comment]
This is a serious issue, because there is no real work around for it. If you have multimedia components with metadata fields, you simply cannot model the metadata fields at the moment. I think it should be labeled as a bug.

**Comment by RaimondKempees** [comment]
It's an enhancement, as apparently Multimedia component metadata is now
pushed in the Json. In version 2.0.2 of the TBBs it is not (or can't get it
to work). Whatever I do, there's no MetadataField filled for MM components.
Maybe that's it? Which TBB version are you on?

**Comment by quirijnslings** [comment]
I'm pretty sure metadata on multimedia components was always there. It is definitely there in my JSON now. I don't have access to it now, but I can share it later.

**Comment by RaimondKempees** [comment]
At this moment, the only way to get both MM Component metadata and the Multimedia node, is to create a ViewModelProperty of type Component.

A better solution would be to be able to have metadata on the Multimedia node and as a third option to enable this in STMs.

**Comment by RaimondKempees** [comment]
This is now possible. Full example:

```
@ViewModel
public class Image extends TridionViewModelBase {

    @ViewModelProperty(isMetadata = true)
    private String focusPoint;

    @ViewModelProperty(entityFieldName = "Url")
    private String url;


    @ViewModelProperty(entityFieldName = "Height")
    private int height;

    @ViewModelProperty(entityFieldName = "Width")
    private int width;

    @ViewModelProperty(entityFieldName = "Size")
    private Integer size;

    public String getFocusPoint () {
        return focusPoint;
    }

    public void setFocusPoint (final String focusPoint) {
        this.focusPoint = focusPoint;
    }

    public String getUrl () {
        return url;
    }

    public void setUrl (final String url) {
        this.url = url;
    }

    public int getHeight () {
        return height;
    }

    public void setHeight (final int height) {
        this.height = height;
    }

    public int getWidth () {
        return width;
    }

    public void setWidth (final int width) {
        this.width = width;
    }

    public Integer getSize () {
        return size;
    }

    public void setSize (final Integer size) {
        this.size = size;
    }
}
```
