### ISSUE TITLE
Allow multiple target schemas for a link field

### ISSUE THREAD

**Issue by quirijnslings** [dd4t/dd4t-2-java#80]
I would like to be able to point a component link field to a range of schemas. My preferred solution would be to link to an interface. For example, I can make a number of models implement the 'Linkable' interface. Whenever I have a link field which could point to any Linkable model, I want to be able to model it like this:

@ViewModelProperty
private Linkable myLinkField;

Since Linkable is not a concrete class but an interface, we need to find a way to provide the concrete class to the deserializer. This information is available if you look up the applicable model classes by root element name. If more than one class is found, the first one should be selected.

This would solve TheMiXeD's problem as well: http://tridion.stackexchange.com/questions/14775/how-to-put-multiple-values-with-multiple-schemas-into-dd4t-2-java.

**Comment by RaimondKempees** [comment]
Fixed in version 2.0.7
