### ISSUE TITLE
Set IsDynamic on TridionViewModelBase

### ISSUE THREAD

**Issue by quirijnslings** [dd4t/dd4t-2-java#82]
Currently the viewmodels do not know whether they are created from an embedded or a dynamic component presentation. This makes it hard to write out the correct XPM markup.
There is a work-around in the XPMComponentPresentationTag class: it reads the 'isDynamic' value from an attribute on the request. I think that is quite ugly. Also, it makes it hard to port the tag to Thymeleaf (which is what I am doing at the moment).
Would it be possible to set the isDynamic property on the entity (TridionViewModelBase) during the databinding proccess?

**Comment by RaimondKempees** [comment]
That's possible. It will be put in 2.0.7.
