### ISSUE TITLE
NoCacheProvider causes null reference exception

### ISSUE THREAD

**Issue by rsleggett** [dd4t/dd4t-2-java#88]
Just trying to upgrade from DD4T 2.0.7 to DD4T 2.0.10 on Web 8.5

> 2017-05-22 16:20:43,109 DEBUG PageFactoryImpl - Enter findPageByUrl with url: /index.html and publicationId: 5
> 2017-05-22 16:20:43,110 DEBUG NoCacheProvider - Nothing to load by design.
> 2017-05-22 16:20:43,125 ERROR Performance - 2b4a9c39-a36b-42ed-8473-bbb1531fe6e5_/_index.html: Error while executing PageFactoryAdapter.findPageByUrl(..)
> java.lang.NullPointerException: null
> 	at org.dd4t.core.factories.impl.PageFactoryImpl.findPageByUrl(PageFactoryImpl.java:157) ~[dd4t-core-2.0.10.jar:na]

I think this is because the CacheProvider is returning null where PageFactoryImpl is expecting a cache element:

     CacheElement cacheElement = this.cacheProvider.loadPayloadFromLocalCache(cacheKey);
     Page page;
     // Line 112 below throws exception
     if(!cacheElement.isExpired() && cacheElement.getPayload() != null) {

**Comment by rsleggett** [comment]
Looks like this might have been fixed on develop

**Comment by RaimondKempees** [comment]
Fixed in 2.0.11 and 2.1.0-beta2
