### ISSUE TITLE
RichTextUtils.resolveXhtmlField(..) pretty-prints the XHtmlField it is given, which can sometimes change how the HTML is rendered by browsers

### ISSUE THREAD

**Issue by garethdanielsmith-connect** [dd4t/dd4t-2-java#92]
To reproduce this issue, call `RichTextUtils.resolveXhtmlField(..)` with an `XHtmlField` containing the string `"O<sub>2</sub>"`.

After the method has been called, the field will contain an extra newline ```"O\n<sub>2</sub>"```

This extra whitespace causes a gap to appear between the O and the subscript 2 when the HTML is rendered by browsers.

It would be good if either pretty-printing was not the default behaviour, or if there was some way of turning it off.

**Comment by RaimondKempees** [comment]
Fixed in 2.1.0-beta4 and 2.0.12
