### ISSUE TITLE
Consider changing the "Not possible to resolve url for component" log message back to debug (currently it is warn)

### ISSUE THREAD

**Issue by garethdanielsmith-connect** [dd4t/dd4t-2-java#93]
In DD4T1 this log message was at debug level: https://github.com/dd4t/dynamic-delivery-4-tridion/blob/29bfc01643093398fe3404db56bf0219919697df/java/dd4t-core/src/main/java/org/dd4t/core/resolvers/impl/DefaultLinkResolver.java#L101

But in DD4T2 it is at warn level: https://github.com/dd4t/dd4t-2-java/blob/7404f2ab92436de4cf7e0a5c4c1b10cfffa65d50/dd4t-core/src/main/java/org/dd4t/core/resolvers/impl/DefaultLinkResolver.java#L103

We are currently upgrading to DD4T2, and we have noticed lots of new warnings in our logs. Upon investigation, I have discovered that these were previously just debug messages, and as such we never saw them.

We could change our logging configuration to ignore warnings for `DefaultLinkResolver`, but I wonder if it would make sense to change the logging statement back to debug level? Not being able to resolve a component to a Url is not always an indication of something that is wrong - I think it can happen if the component has not been published, for example, or if the component was published, but is not a top-level component on a page.

**Comment by RaimondKempees** [comment]
Fixed. Will be in 2.0.12 and 2.1.0-beta4
