### ISSUE TITLE
org.dd4t.core.factories.impl.BinaryFactoryImpl has no public constructor

### ISSUE THREAD

**Issue by ghost** [dd4t/dd4t-2-java#98]
Can this class have a public constructor?

Right now I have to create a subclass in the same package, with a public constructor, in order to use the functionality that BinaryFactoryImpl contains.

**Comment by RaimondKempees** [comment]
Yes it can.

**Comment by garethdanielsmith-connect** [comment]
Awesome, thanks 👍
