### ISSUE TITLE
org.dd4t.mvc.controllers.AbstractBinaryController prevents error pages being shown

### ISSUE THREAD

**Issue by ghost** [dd4t/dd4t-2-java#99]
`org.dd4t.mvc.controllers.AbstractBinaryController` has a final block that calls `response.getOutputStream().close()` even when the output stream was never get-ted in the first place.

This means that when there is an error like when an image can't be found, Spring can't show the error page because it can't write any output to the response.

The offending code is here:

https://github.com/dd4t/dd4t-2-java/blob/ac27682adf03a7002b4707cfe2f9a3068b558195/dd4t-mvc-support/src/main/java/org/dd4t/mvc/controllers/AbstractBinaryController.java#L142

I suggest that the code be changed to only close the stream if it was actually used in the first place.

**Comment by RaimondKempees** [comment]
Will be available in 2.1.0

**Comment by Dretch** [comment]
Thanks @RaimondKempees
